# Default state for all rules
default: true

# MD013/line-length - Ignore Line length
MD013: false

# MD033/no-inline-html - Allow lists in tables
MD033:
  allowed_elements:
    - "li"
    - "ul"
    - "summary"
    - "details"

# This rule conflicts with issue templates
MD041: false
