language: python
cache: pip
dist: focal
sudo: false

matrix:
    include:
        - python: '3.6'
        - python: '3.7'
        - python: '3.8'
        - python: '3.9'
        - python: '3.10'

install:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt
    - pip install python-coveralls
    - pip install .

script:
    - make lint && make ci

after_success:
    - make coverage
