name: Feature Request
description: Request a new feature
title: "[FEATURE]: "
labels: ["enhancement"]
assignees:
  - xakepnz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: details
    attributes:
      label: Feature Details
      description: Also attach any relevant screenshots/docs/links.
      placeholder: Tell us what you want to see!
      value: "Details of feature..."
    validations:
      required: true
